# Generated by Django 4.1 on 2022-08-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.UUIDField(
                default="A178C47C4", editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="type",
            field=models.CharField(
                choices=[("visa", "Visa"), ("mastercard", "Mastercard")], max_length=10
            ),
        ),
    ]
