# Generated by Django 4.1 on 2022-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_wallet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(
                default="6AEF4B9A",
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
