# Generated by Django 4.1 on 2022-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_wallet_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
