# Generated by Django 4.1 on 2022-08-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_wallet_id_alter_wallet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(
                default="55017779", editable=False, max_length=8, unique=True
            ),
        ),
    ]
