# Generated by Django 4.1 on 2022-08-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0009_alter_transaction_receiver_alter_transaction_sender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="commission",
            new_name="commision",
        ),
    ]
