# Generated by Django 4.1 on 2022-08-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0010_rename_commission_transaction_commision"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
